### ISSUE TITLE
TodoistPageTemplate not exposes in Plugin Settings in the latest release

### ISSUE THREAD

**Issue by geekifier** [stuporfly/ObsidianTodoistProjects#4]
Thanks for working on this plugin, it's looking good and super useful!

I noticed a small issue with the "release" version, `0.1.3`. I downloaded the manifest.json and main.js, everything works fine, but the `TodoistPageTemplate` is not available in the Plugin Options.

![image](https://github.com/user-attachments/assets/94b8ddb4-9ddf-48c4-bd73-705b8cfc1ab3)

Let me know if there is anything else I should try to help debug this?

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.8
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 23.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: off
	Base theme: adapt to system
	Community theme: Minimal v7.7.7
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 31
	Plugins enabled: 26
		1: Leaflet v6.0.5
		2: Advanced Tables v0.21.0
		3: Excalidraw v2.2.9
		4: Dataview v0.5.67
		5: Kanban v2.0.51
		6: Local Images Plus v0.15.9
		7: Natural Language Dates v0.6.2
		8: Local REST API v2.4.3
		9: Omnivore v1.10.3
		10: Calendar v1.5.10
		11: Recent Files v1.4.1
		12: Settings Search v1.3.10
		13: Book Search v0.7.4
		14: Plugin Update Tracker v1.5.2
		15: Projects v1.17.3
		16: Todoist Sync v1.13.0
		17: Auto Link Title v1.5.4
		18: Linter v1.25.0
		19: Tag Wrangler v0.6.1
		20: Symbols Prettifier v1.1.4
		21: Minimal Theme Settings v8.0.2
		22: Image Toolkit v1.4.1
		23: Templater v2.3.3
		24: Various Complements v10.0.0
		25: Callout Manager v1.1.0
		26: Todoist Project sync v0.1.3
```

P.S. Seems the default template also needs to be updated to the new [YAML syntax](https://jamiebrynes7.github.io/obsidian-todoist-plugin/docs/query-blocks). This is the reason why I was looking for the setting.

**Comment by stuporfly** [comment]
The "TodoistPageTemplate" was unfinished functionality - I have commented out the setting, until I have time to implement it correctly, and created a 0.1.4 release.

**Comment by stuporfly** [comment]
I have now updated the hard-coded template to use YAML syntax as well, and created release 0.1.5
